--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ZzKino/EasyWing
build-by-default: true
branches:
- master
projects:
  EasyWing:
    iocn: icon.png
    path: "" 
    libs:
    - src: jojoe77777/FormAPI/LibFormAPI
      version: ^1.0.0
...
